openapi: 3.0.2
info:
  description: Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
  version: v1
  title: WIRE API
  contact:
    url: https://github.com/moov-io/wire
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8087
    description: Local development

tags:
  - name: Files
    description: |
      File contains FEDWireMessages of a WIRE File.

paths:
  /ping:
    get:
      tags:
        - Files
      summary: Ping the Wire service to check if running
      operationId: ping
      responses:
        '200':
          description: Service is running properly
  /files:
    get:
      tags:
        - Files
      summary: Gets a list of Files
      operationId: getFiles
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          description: A list of File objects
          headers:
            X-Total-Count:
              description: The total number of WIRE files
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Files'
  /files/create:
    post:
      tags:
        - Files
      summary: Create a new File object
      operationId: createFile
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/requestId'
        - $ref: '#/components/parameters/idempotencyKey'
      requestBody:
        description: Content of the WIRE file (in json or raw text)
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFile'
          text/plain:
            schema:
              description: A plaintext FED WIRE file
              type: string
              example:
      responses:
        '201':
          description: A JSON object containing a new File
          headers:
            Location:
              description: The location of the new resource
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '400':
          description: "Invalid File Header Object"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /files/{file_id}:
    get:
      tags:
        - Files
      summary: Retrieves the details of an existing File. You need only supply the unique File identifier that was returned upon creation.
      operationId: getFileByID
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: file_id
          in: path
          description: File ID
          required: true
          schema:
            type: string
            example: 3f2d23ee214
      responses:
        '200':
          description: A File object for the supplied ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '404':
          description: A resource with the specified ID was not found
    post:
      tags:
        - Files
      summary: Updates the specified FedWire Message by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
      operationId: updateFile
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/requestId'
        - $ref: '#/components/parameters/idempotencyKey'
        - name: file_id
          in: path
          description: File ID
          required: true
          schema:
            type: string
            example: 3f2d23ee214
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFile'
      responses:
        '201':
          description: A JSON object containing a new File
          headers:
            Location:
              description: The location of the new resource
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '400':
          description: "Invalid File Header Object"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Files
      summary: Permanently deletes a File and associated Batches. It cannot be undone.
      operationId: deleteWIREFile
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - name: file_id
          in: path
          description: File ID
          required: true
          schema:
            type: string
            example: 3f2d23ee214
        - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          description: Permanently deleted File.
        '404':
          description: A File with the specified ID was not found.
components:
  schemas:
    CreateFile:
      properties:
        id:
          type: string
          description: File ID
          example: 3f2d23ee214
        fedWireMessage:
          type: array
          items:
            $ref: '#/components/schemas/FEDWireMessage'
    File:
      properties:
        id:
          type: string
          description: File ID
          example: 3f2d23ee214
        fedWireMessage:
          items:
            $ref: '#/components/schemas/FEDWireMessage'
      required:
        - fedWireMessage
    FEDWireMessage:
      description: FEDWireMessage
      properties:
        senderSuppliedInformation:
          description: SenderSuppliedInformation {1500}
          $ref: '#/components/schemas/SenderSuppliedInformation'
        typeSubType:
          description: TypeSubType {1510}
          $ref: '#/components/schemas/TypeSubType'
        inputMessageAccountabilityData:
          description: InputMessageAccountabilityData {1520}
          $ref: '#/components/schemas/InputMessageAccountabilityData'
        amount:
          description: Amount {2000}
          $ref: '#/components/schemas/Amount'
        senderDepositoryInstitution:
          description: SenderDepositoryInstitution {3100}
          $ref: '#/components/schemas/SenderDepositoryInstitution'
        receiverDepositoryInstitution:
          description: ReceiverDepositoryInstitution {3400}
          $ref: '#/components/schemas/ReceiverDepositoryInstitution'
        businessFunctionCode:
          description: BusinessFunctionCode {3600}
          $ref: '#/components/schemas/BusinessFunctionCode'
        # ToDo: Other Transfer Information
        intermediaryFinancialInstitution:
          description: IntermediaryFinancialInstitution {3400}
          $ref: '#/components/schemas/IntermediaryFinancialInstitution'
      required:
        - senderSuppliedInformation
        - typeSubType
        - inputMessageAccountabilityData
        - amount
        - senderDepositoryInstitution
        - receiverDepositoryInstitution
        - businessFunctionCode
    SenderSuppliedInformation:
      description: SenderSuppliedInformation {1500}
      properties:
        formatVersion:
          type: string
          minLength: 2
          maxLength: 2
          description: |
            FormatVersion
            30
          example: '30'
        userRequestCorrelation:
          type: string
          minLength: 8
          maxLength: 8
          description: UserRequestCorrelation
          example: 'XYZ'
        testProductionCode:
          type: string
          minLength: 1
          maxLength: 1
          description: |
            TestProductionCode
            T: Test
            P: Production
          example: 'T'
        messageDuplicationCode:
          type: string
          minLength: 1
          maxLength: 1
          description: |
            MessageDuplicationCode
            '': Original Message
            P: Resend
          example: ''
      required:
        - formatVersion
        - userRequestCorrelation
        - testProductionCode
        - messageDuplicationCode
    TypeSubType:
      description: TypeSubtype {1510}
      properties:
        typeCode:
          type: string
          minLength: 2
          maxLength: 2
          description: TypeCode
          example: '10'
        subTypeCode:
          type: string
          minLength: 2
          maxLength: 2
          description: SubTypeCode
          example: '00'
      required:
        - typeCode
        - subTypeCode
    InputMessageAccountabilityData:
      description: Input Message Accountability Data (IMAD) {1520}
      properties:
        inputCycleDate:
          type: string
          minLength: 8
          maxLength: 8
          description: |
            InputCycleDate
            CCYYMMDD
          example: 20191201
        inputSource:
          type: string
          minLength: 8
          maxLength: 8
          description: InputSource
          example: 'XYZ ABC '
        inputSequenceNumber:
          type: string
          minLength: 6
          maxLength: 6
          description: InputSequenceNumber
          example: '000001'
      required:
        - inputCycleDate
        - inputSource
        - inputSequenceNumber
    Amount:
      description: Amount (up to a penny less than $10 billion) {2000}
      properties:
        amount:
          type: string
          minLength: 12
          maxLength: 12
          description: |
            Amount
            12 numeric, right-justified with leading zeros, an implied decimal point and no commas;
            e.g., $12,345.67 becomes 000001234567
            Can be all zeros for subtype 90
          example: '000000100000'
      required:
        - amount
    SenderDepositoryInstitution:
      description: SenderDepositoryInstitution {3100}
      properties:
        senderABANumber:
          type: string
          minLength: 9
          maxLength: 9
          description: SenderABANumber
          example: '091905114'
        senderShortName:
          type: string
          minLength: 18
          maxLength: 18
          description: SenderShortName
          example: 'MIDWESTONE B&T    '
      required:
        - senderABANumber
        - senderShortName
    ReceiverDepositoryInstitution:
      description: Receiver DepositoryInstitution {3400}
      properties:
        receiverABANumber:
          type: string
          minLength: 9
          maxLength: 9
          description: ReceiverABANumber
          example: '091905664'
        receiverShortName:
          type: string
          minLength: 18
          maxLength: 18
          description: ReceiverShortName
          example: 'PREMIER BANK      '
      required:
        - receiverABANumber
        - receiverShortName
    BusinessFunctionCode:
      description: BusinessFunctionCode {3600}
      properties:
        businessFunctionCode:
          type: string
          minLength: 3
          maxLength: 3
          description: |
            BusinessFunctionCode
            BTR: Bank Transfer (Beneficiary is a bank)
            DRC: Customer or Corporate Drawdown Request
            CKS: Check Same Day Settlement
            DRW: Drawdown Payment
            CTP: Customer Transfer Plus
            FFR: Fed Funds Returned
            CTR: Customer Transfer (Beneficiary is a not a bank)
            FFS: Fed Funds Sold
            DEP: Deposit to Senderâ€™s Account
            SVC: Service Message
            DRB: Bank-to-Bank Drawdown Request
          example: 'BTR'
        transactionTypeCode:
          type: string
          minLength: 3
          maxLength: 3
          description: |-
            TransactionTypeCode
            If {3600} is CTR, an optional Transaction Type Code element is permitted;
            however, the Transaction Type Code 'COV' is not permitted.
            ToDo: Research This, I don't understand it yet
          example: '   '
      required:
        - businessFunctionCode
    IntermediaryFinancialInstitution:
      description: IntermediaryFinancialInstitution
      properties:
        idCode:
          type: string
          minLength: 1
          maxLength: 1
          description: |-
            ID Code
            B: SWIFT Bank Identifier Code (BIC)
            C: CHIPS Participant
            D: Demand Deposit Account (DDA) Number
            F: Fed Routing Number
            U: CHIPS Identifier
    Error:
      required:
        - error
      properties:
        error:
          type: string
          description: An error message describing the problem intended for humans.
          example: Validation error(s) present.
  parameters:
    requestId:
      in: header
      name: X-Request-Id
      description: Optional Request ID allows application developer to trace requests through the systems logs
      example: rs4f9915
      schema:
        type: string
    idempotencyKey:
      in: header
      name: X-Idempotency-Key
      description: Idempotent key in the header which expires after 24 hours. These strings should contain enough entropy for to not collide with each other in your requests.
      example: a4f88150
      required: false
      schema:
        type: string
